version: "3.9"

services:
  aggynfrens-api:
    container_name: aggynfrens-api
    build:
      context: .
      dockerfile: ./aggynfrens.Dockerfile
    # restart: unless-stopped
    networks:
      - net-one
    depends_on:
      # - redis
      - postgres
  
  # postgres:
  #   container_name: anf-postgres-server
  #   image: docker.io/library/postgres:15-alpine
  #   # restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD?"DB_PASSWORD not set."}
  #     POSTGRES_USER: ${DB_USERNAME?"DB_USERNAME not set."}
  #     # POSTGRES_DB: ${DB_DATABASE_NAME?"DB_DATABASE_NAME not set."}
  #     PG_DATA: /var/lib/postgresql/data
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - net-one
  #   # expose:
  #   #     - "5432"

  # redis:
  #   profiles:
  #     - disabled
  #   container_name: aggynfrens-redis-server
  #   image: redis:7-alpine
  #   # restart: unless-stopped
  #   volumes:
  #     - redisdata:/var/lib/redis/data
  #   networks:
  #     - net-one
  #   # expose:
  #   #     - "6379"

networks:
  net-one:

volumes:
  redisdata:
  pgdata:
