version: "3.9"

services:
  postgres:
    container_name: aggy-postgres-server-dev
    env_file:
      - .env
    ports:
      - "5432:5432"
  # redis:
  #   profiles:
  #     - disabled
  #   container_name: aggy-redis-server-dev
  #   env_file:
  #     - .env
  #   ports:
  #     - "6379:6379"
