set shell := ["sh", "-c"]
set dotenv-load

# List the avail commands
default:
  @just --list --unsorted

# psql from the db running in the compose launched pg container
psql:
  podman exec -it aggy-postgres-server-dev psql -U aggy

# psql command but fit for redirects
psql-tty *ARGS:
  podman exec -i aggy-postgres-server-dev psql -U aggy {{ARGS}}

# The flyway cli tool
flyway *ARGS:
  podman-compose  --profile tools run --rm flyway {{ARGS}}

# Apply migrations to database.
db-mig:
  @just flyway migrate

# Apply migrations to database.
db-reset:
  cargo sqlx database drop -y
  cargo sqlx database create
  @just flyway migrate

alias dev := dev-up

# Start all services required for development
dev-up:
  podman-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

test *ARGS:
  cargo nextest run {{ARGS}}
